package PipesInTheDesert.GUI.Observer;

public enum ChangeType {
    POSITION_CHANGED,
    HEALTH_CHANGED,
    LEAK_CHANGED,
    FLOW_CHANGED,
    OCCUPANT_CHANGED,
    STAMINA_CHANGED,
    INPUT_OUTPUT_CHANGE,
    TANK_CHANGED,
    THROUGHPUT_CHANGE,
    GENERATION_CHANGE,
    HELD_ITEM_CHANGED
}

